run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - typecheck

linters-settings:
  staticcheck:
    checks: ["-SA5011"]

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
        - ineffassign
    - path: examples/
      linters:
        - errcheck
